return {
  AVG_BtnCancel = "取 消",
  AVG_BtnConfim = "确 定",
  AVG_ImportantChoice = "选项 %d",
  AVG_ImportantChoice_BE = "通向BE结局",
  AVG_ImportantChoice_Choosed = "已选择过此项",
  AVG_ImportantChoice_Disable = "已经去过这里了",
  AVG_ImportantChoice_Match = "此分支对应选项",
  AVG_ImportantChoice_UnknownDesc = "掌握更多情报的话……",
  AVG_ImportantChoice_UnknownTitle = "未知的道路",
  AVG_ImportantChoice_NewChoiceTips1 = "新的选择出现了",
  AVG_ImportantChoice_NewChoiceTips2 = "最终的道路",
  AVG_Log_Choice_Title = "%s 选择了",
  AVG_Log_Thought_Title = "%s 心想......",
  AVG_Log_Title = "记录",
  AVG_PersonalityChoice_Choosed = "上次选择",
  Menu_HideUI = "隐藏界面",
  Menu_Log = "记录",
  Menu_Skip = "跳过",
  SEX = {
    ["==SEX1=="] = {"她", "他"},
    ["==SEX2=="] = {"姐姐", "哥哥"},
    ["==SEX3=="] = {"大姐姐", "大哥哥"},
    ["==SEX4=="] = {"妹妹", "弟弟"},
    ["==SEX5=="] = {"小妹妹", "小弟弟"},
    ["==SEX6=="] = {"女皇", "国王"},
    ["==SEX7=="] = {"小姐", "先生"},
    ["==SEX8=="] = {"公主", "王子"},
    ["==SEX9=="] = {"小女孩", "小男孩"},
    ["==SEX10=="] = {"姐妹", "姐弟"},
    ["==SEX11=="] = {"老太太", "老头子"},
    ["==SEX12=="] = {"脖颈", "腰间"},
    ["==SEX13=="] = {
      "白发的少女",
      "黑发的少年"
    },
    ["==SEX14=="] = {"白头发", "黑头发"},
    ["==SEX15=="] = {"姑娘", "小伙"},
    ["==SEX16=="] = {"魔女", "男巫"},
    ["==SEX17=="] = {"少女", "少年"},
    ["==SEX18=="] = {"裙子", "裤子"},
    ["==SEX19=="] = {"女仆", "管家"},
    ["==SEX20=="] = {"衬衣", "中衣"},
    ["==SEX21=="] = {"小姐", "小哥"},
    ["==SEX=="] = {"女士", "先生"}
  },
  SkipBETips = "跳过结局后，将返回到上一个选项处。是否确认？==RT==（后续您可以随时回看已解锁的结局）",
  SkipTips = "确定跳过这个剧情吗？",
  SkipWinTitle = "跳过剧情"
}
