return {
  AVG_BtnCancel = "Cancel",
  AVG_BtnConfim = "Confirm",
  AVG_ImportantChoice = "Option %d",
  AVG_ImportantChoice_BE = "Leads to Bad Ending",
  AVG_ImportantChoice_Choosed = "Selected",
  AVG_ImportantChoice_Disable = "Selected",
  AVG_ImportantChoice_Match = "This branch corresponds to...",
  AVG_ImportantChoice_UnknownDesc = "Did you miss something?",
  AVG_ImportantChoice_UnknownTitle = "Unknown Lead",
  AVG_Log_Choice_Title = "%s has selected",
  AVG_Log_Thought_Title = "%s thinks...",
  AVG_Log_Title = "Records",
  AVG_PersonalityChoice_Choosed = "Last Selection",
  Menu_HideUI = "Hide",
  Menu_Log = "Records",
  Menu_Skip = "Skip",
  SEX = {
    ["==SEX10=="] = {"sisters", "brothers"},
    ["==SEX11=="] = {"lady", "lord"},
    ["==SEX12=="] = {"Lady", "Lord"},
    ["==SEX13=="] = {"lady", "gentleman"},
    ["==SEX14=="] = {"white hair", "black hair"},
    ["==SEX15=="] = {"woman", "man"},
    ["==SEX16=="] = {"witch", "wizard"},
    ["==SEX17=="] = {"Miss", "Mister"},
    ["==SEX18=="] = {"skirt", "pant"},
    ["==SEX19=="] = {"maid", "butler"},
    ["==SEX1=="] = {"She", "He"},
    ["==SEX20=="] = {"shirt", "undershirt"},
    ["==SEX21=="] = {"lady", "gentleman"},
    ["==SEX2=="] = {"Her", "His"},
    ["==SEX3=="] = {"her", "his"},
    ["==SEX4=="] = {"her", "him"},
    ["==SEX5=="] = {"hers", "his"},
    ["==SEX6=="] = {"Ms.", "Mr."},
    ["==SEX7=="] = {"Miss", "Mr."},
    ["==SEX8=="] = {"herself", "himself"},
    ["==SEX9=="] = {"girl", "boy"},
    ["==SEX=="] = {"she", "he"}
  },
  SkipBETips = "Skipping an ending will return you to the previous choice. Continue?",
  SkipTips = "Do you want to skip the story?",
  SkipWinTitle = "Skip"
}
